fireflyprotocol/firefly-client

- src/fireflyClient.ts
- added 1 minute expiration for MARKET order
> [BFLY-714] Added Expiration For Market Order

- package.json
- yarn.lock
- fixed library and math version
- bumped version
> fixed library version and bumped version

- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
- update adjustLeverage contract call
- add add margin function
- add remove margin function
- fixed issues after bumping `library` version
> [BFLY-790] update contract calls

- package.json
- yarn.lock
> Fixed build issue

- package.json
- src/constants.ts
- src/exchange/apiService.ts
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
- fixed getContractAddresses
- fixed auth issue
- wrote set and get leverage test
- bumped version to 1.0.27
> [BFLY-832] Fixed New Deployment Issues

- package.json
- src/constants.ts
- src/exchange/apiService.ts
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
> [BFLY-845] bump library in client

- package.json
- src/exchange/apiService.ts
- src/fireflyClient.ts
- changed all functions to arrow functions
- made userOnboarding function public to use on frontend
- fixed onboard signer method
> [BFLY-852] Onboard Signer Fix For UI

- package.json
- src/exchange/apiService.ts
- src/exchange/apiUrls.ts
- src/exchange/sockets.ts
- src/interfaces/routes.ts
- yarn.lock
- bumped library package
- bumped maths package
- removed bignumber.js dependency
> [BFLY-896] Fixed vulnerable packages

- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- Returning balance of user in USDC and MarginBank in number format
- Bumped version
- Updated tests
> Return Values Update

- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
> [BFLY-1059] Test fixes

- package.json
- src/fireflyClient.ts
- onboard signer web3 provider fix for ui integration
> Signer Fixes For Perpetual UI

- examples/9.create-signed-order.ts
- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
- Updated contract factories 
- Updated order signer
- Fixed tests
- Bumped version to 1.0.58
> Update Order Signer

- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- yarn.lock
- fixed withdraw margin corner case
> [BFLY-1055] Withdraw Margin Failing

- package.json
- src/exchange/contractService.ts
- src/fireflyClient.ts
- src/interfaces/routes.ts
- tests/fireflyClient.test.ts
- fixed status param in getOrderRequest interface
- removed await from adjustLeverage contract call for UI
> Statuses param fixed in GetOrderRequest

- package.json
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- added pending and partial filled status in get orders call when cancelling
- fixed tests
> Get `Pending` and `Partial Filled` orders when Cancelling

- src/interfaces/routes.ts
- added missing keys in MarketData interface
> Fix Market Data Interface

- package.json
- src/fireflyClient.ts
- fixed incorrect description of methods
> Updated Method Descriptions

- package.json
- src/exchange/biconomyService.ts
- src/exchange/contractService.ts
- tests/fireflyClient.test.ts
- Updated wallet check condition
> Updated wallet check conditions in contract services

- package.json
- src/exchange/apiUrls.ts
- src/fireflyClient.ts
- src/interfaces/routes.ts
- tests/fireflyClient.test.ts
- Added missing routes
- Matched interfaces with api responses
> [EXC-1] Public Documentation Missing Routes

- package.json
- src/interfaces/routes.ts
- tests/fireflyClient.test.ts
- update getOrderRequest params
> [EXC-78] Add Order Hash Param In Get Order Route

- src/constants.ts
- src/exchange/biconomyService.ts
- src/exchange/contractService.ts
- src/fireflyClient.ts
- tests/fireflyClient.test.ts
- Estimated gas fee for contract calls if netwrok is arbitrum
> [EXC-141] Fixed Incorrect Gas Fee For Arbitrum

- package.json
> Bumped Package Version

- README.md
- package.json
Added badges related to version, build and licence and patch version updated
> BFLY-1273  Added badges

- package.json
- src/exchange/contractErrorHandling.service.ts
- updated the error message for restricted users on the basis of the response from verify deposit endpoint.
> Updated Restricted User Error Message

- package.json
- src/fireflyClient.ts
- src/interfaces/routes.ts
- tests/fireflyClient.test.ts
Change parentAccountAddress to parentAddress to make consistent with others
> [EXC-586] Change Naming Convention

- package.json
- src/interfaces/routes.ts
Replace index price with oracle price in parameters and variables.
Updated the version
> [QUANT-409] Replace Index Price with Oracle Price

- src/interfaces/routes.ts
simple fix, btw, I find out the market data streaming seems not work, it never call back the callback function
> fix typo in marketdata

- package.json
- src/fireflyClient.ts
- Removed restriction of stop orders on prod
> [EXC-899] Allowed Stop Orders On Prod

- src/fireflyClient.ts
-Added error handling on get and post calls for resetCounter when pods are down
> [EXC-908] add error handling for when dms pods are down

- .github/workflows/security-pipeline.yml
> Added security-pipeline

- package.json
- src/exchange/WebSocket.ts
- src/exchange/sockets.ts
- src/interfaces/routes.ts
- tests/fireflyClient.test.ts
- yarn.lock
- Added socket interfaces for sent for settlement and re-queue notifications
> Added New Socket Events Usage

- package.json
- src/exchange/contractService.ts
- src/fireflyClient.ts
- src/interfaces/routes.ts
- yarn.lock
- Added adjust leverage signing method and API call
> [EXC-1872] Update Adjust Leverage To Sign Transaction & Make API Call
